name: Test

on:
  push:
    branches:
      - main
      - develop
      - rc
  pull_request:

env:
  PRIVATE_KEY_ANVIL: ${{ secrets.PRIVATE_KEY_ANVIL }}
  PRIVATE_KEY_SEPOLIA: ${{ secrets.PRIVATE_KEY_SEPOLIA }}
  PRIVATE_KEY_84532: ${{ secrets.PRIVATE_KEY_84532 }}
  PRIVATE_KEY_11155111: ${{ secrets.PRIVATE_KEY_11155111 }}
  PROVIDER_URI_SEPOLIA: ${{ secrets.PROVIDER_URI_SEPOLIA }}
  PROVIDER_URI_GOERLI: ${{ secrets.PROVIDER_URI_GOERLI }}
  PROVIDER_URI_1: ${{ secrets.PROVIDER_URI_1 }}
  PROVIDER_URI_84532: ${{ secrets.PROVIDER_URI_84532 }}
  PROVIDER_URI_11155111: ${{ secrets.PROVIDER_URI_11155111 }}
  PINATA_JWT: ${{ secrets.PINATA_JWT }}

jobs:
  circuit:
    name: Circuit & QueryBuilder Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: "Install Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: "20.x"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: circuit/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ./circuit
        run: pnpm install

      - name: Run Unit Tests
        working-directory: ./circuit
        run: pnpm test
    
  client-unit-tests:
    name: Client Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: "Install Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: "20.x"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: client/pnpm-lock.yaml

      - name: Set all packages to local and build
        working-directory: ./
        run: pnpm local

      - name: Run Unit Tests (Client)
        working-directory: ./client
        run: pnpm test test/unit

  harness-integration-tests-11155111:
    name: "Harness: Client Integration Tests (11155111)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: "Install Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: "20.x"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: client/pnpm-lock.yaml

      - name: Set all packages to local and build
        working-directory: ./
        run: pnpm local

      - name: Run Integration Tests (Client)
        working-directory: ./harness
        run: CHAIN_ID=11155111 pnpm test test/integration/start.test.ts
  
  harness-integration-tests-84532:
    name: "Harness: Client Integration Tests (84532)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: "Install Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: "20.x"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: client/pnpm-lock.yaml

      - name: Set all packages to local and build
        working-directory: ./
        run: pnpm local

      - name: Run Integration Tests (Client)
        working-directory: ./harness
        run: CHAIN_ID=84532 pnpm test test/integration/start.test.ts
